# Generated by Django 2.0.2 on 2018-02-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photourl', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='park',
            name='formatted_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='photos',
            field=models.ManyToManyField(blank=True, to='park.Photo'),
        ),
    ]
