# Generated by Django 2.0.2 on 2018-02-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_auto_20180213_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='park',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='park.Review'),
        ),
    ]
