# Generated by Django 2.0.2 on 2018-02-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0003_auto_20180213_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mark',
            field=models.NullBooleanField(),
        ),
    ]
